### ISSUE TITLE
Can't get out of the camera

### ISSUE THREAD

**Issue by Rick160601** [jasonpaulos/ArrowCamMod#1]
when I shoot an arrow and hold c, it shows the shooting of the arrow and where it lands and stays there, however there is no way of getting out of this camera mode again so I have to restart my world. now, my view is f*cked up and tapping the F5 button doesn't help out. so I have to restart minecraft. I do have other mods installed aswell: (see .zip file)
[1.8 minecraft Curse file.zip](https://github.com/jasonpaulos/ArrowCamMod/files/454077/1.8.minecraft.Curse.file.zip)

Edit: this is been an Issue eversince I first downloaded the mod in, if I remember correctly, 2014 in minecraft 1.7.10

**Comment by jasonpaulos** [comment]
Are you sure this happens when using the most recent version of my mod? I have never encountered an issue like this before.

Try downloading the most recent version from here and let me know if the issues persist: https://minecraft.curseforge.com/projects/arrow-cam/files
