### ISSUE TITLE
Possible Incompatibility with Infernalmobs?

### ISSUE THREAD

**Issue by APolarBaer** [jasonpaulos/ArrowCamMod#2]
http://pastebin.com/cD61k934

happens when firing an arrow and holding shift on SMP

**Comment by APolarBaer** [comment]
Possibly fixed, waiting for update push to test

**Comment by jasonpaulos** [comment]
Looks like the fix on Atomic Stryker's end should clear up the issue. Thanks for reporting this, let me know if any other issues arise.
