### ISSUE TITLE
Unrelated to this project

### ISSUE THREAD

**Issue by FantomHD** [jasonpaulos/ArrowCamMod#3]
Hey man, I couldn't find any other way to contact you, so I had to do this lol. So I saw your comment from a while back on socketclusters about getting it to work with passport steam. You seemed to have eventually gotten it down, but I cant. Anyway you could send me the source of just authenticating steam w/ passport and keeping the userid's in the socket? Any help is really appreciated if you cant send any pieces of the source. Thanks in advanced :)

[Comment In Question](https://github.com/SocketCluster/socketcluster/issues/53)

**Comment by jasonpaulos** [comment]
It seems like you already found a solution [here](https://github.com/SocketCluster/socketcluster/issues/259), but I'd be happy to help if you still need it!

**Comment by FantomHD** [comment]
Yup I got it, thanks anyway man!
